/*
 * moteur.c
 *
 *  Created on: 26 juin 2019
 *      Author: Nirgal
 */

#include "moteur.h"
#include "config.h"
#include "stm32f1_gpio.h"
#include "stm32f1_pwm.h"

#define PWM_PERIOD 50 //periode du pwm en us


void MOTEUR_init(void)
{
	BSP_GPIO_PinCfg(MOTEUR_GPIO, MOTEUR_AIN1, GPIO_MODE_OUTPUT_PP,GPIO_NOPULL,GPIO_SPEED_FREQ_HIGH);
	BSP_GPIO_PinCfg(MOTEUR_GPIO, MOTEUR_AIN2, GPIO_MODE_OUTPUT_PP,GPIO_NOPULL,GPIO_SPEED_FREQ_HIGH);
	BSP_GPIO_PinCfg(MOTEUR_GPIO, MOTEUR_BIN1, GPIO_MODE_OUTPUT_PP,GPIO_NOPULL,GPIO_SPEED_FREQ_HIGH);
	BSP_GPIO_PinCfg(MOTEUR_GPIO, MOTEUR_BIN2, GPIO_MODE_OUTPUT_PP,GPIO_NOPULL,GPIO_SPEED_FREQ_HIGH);
}



void MOTEUR_avance(void)
{
	PWM_run(TIMER1_ID, TIM_CHANNEL_2, FALSE, PWM_PERIOD, 70, FALSE);	//configuration pour AIN1 (sur PA9)
	PWM_run(TIMER1_ID, TIM_CHANNEL_1, FALSE, PWM_PERIOD, 0, FALSE);

	PWM_run(TIMER1_ID, TIM_CHANNEL_3, FALSE, PWM_PERIOD, 70, FALSE);	//configuration pour BIN1 (sur PA10)
	PWM_run(TIMER1_ID, TIM_CHANNEL_4, FALSE, PWM_PERIOD, 0, FALSE);
}
void MOTEUR_recule(void)
{
	PWM_run(TIMER1_ID, TIM_CHANNEL_2, FALSE, PWM_PERIOD, 0, FALSE);	//configuration pour AIN1 (sur PA9)
	PWM_run(TIMER1_ID, TIM_CHANNEL_1, FALSE, PWM_PERIOD, 70, FALSE); //configuration pour AIN2 (sur PA8)

	PWM_run(TIMER1_ID, TIM_CHANNEL_3, FALSE, PWM_PERIOD, 0, FALSE);	//configuration pour AIN1 (sur PA9)
	PWM_run(TIMER1_ID, TIM_CHANNEL_4, FALSE, PWM_PERIOD, 70, FALSE); //configuration pour BIN2 (sur PA11)
}
void MOTEUR_gauche(void)
{

	PWM_run(TIMER1_ID, TIM_CHANNEL_2, FALSE, PWM_PERIOD, 0, FALSE);
	PWM_run(TIMER1_ID, TIM_CHANNEL_1, FALSE, PWM_PERIOD, 70, FALSE);

	PWM_run(TIMER1_ID, TIM_CHANNEL_3, FALSE, PWM_PERIOD, 70, FALSE);
	PWM_run(TIMER1_ID, TIM_CHANNEL_4, FALSE, PWM_PERIOD, 0, FALSE);
}
void MOTEUR_droite(void)
{
	PWM_run(TIMER1_ID, TIM_CHANNEL_2, FALSE, PWM_PERIOD, 70, FALSE);
	PWM_run(TIMER1_ID, TIM_CHANNEL_1, FALSE, PWM_PERIOD, 0, FALSE);

	PWM_run(TIMER1_ID, TIM_CHANNEL_3, FALSE, PWM_PERIOD, 0, FALSE);
	PWM_run(TIMER1_ID, TIM_CHANNEL_4, FALSE, PWM_PERIOD, 70, FALSE);
}
void MOTEUR_arret(void)
{
	PWM_run(TIMER1_ID, TIM_CHANNEL_2, FALSE, PWM_PERIOD, 70, FALSE);
	PWM_run(TIMER1_ID, TIM_CHANNEL_1, FALSE, PWM_PERIOD, 70, FALSE);

	PWM_run(TIMER1_ID, TIM_CHANNEL_3, FALSE, PWM_PERIOD, 70, FALSE);
	PWM_run(TIMER1_ID, TIM_CHANNEL_4, FALSE, PWM_PERIOD, 70, FALSE);
}
